application:
  host: 0.0.0.0
  port: 8080
database:
  host: 127.0.0.1
  port: 5432
  username: "faulty_server_poller_service"
  password: "service_password"
  database: "faulty_server_poller"
  connect_timeout_sec: 2
polling:
  polling_address: "http://faulty-server-htz-nbg1-1.wvservices.exchange:8080"
  max_concurrent_runs: 3
  max_pending_runs: 2
  concurrent_requests_per_run: 3
